// Redesigned pages (current design system, FlowAppShell)
export { HomePage } from './HomePage'
export { SearchPage } from './SearchPage'
export { DailyJokePage } from './DailyJokePage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { GoogleCallbackPage } from './GoogleCallbackPage'
export { FlowPage } from './FlowPage'
export { FlowCanvasPage } from './FlowCanvasPage'
export { ExplorePage } from './ExplorePage'
export { LibraryPage } from './LibraryPage'
export { TrendingPage } from './TrendingPage'
export { FavoritesPage } from './FavoritesPage'
export { DraftsPage } from './DraftsPage'
export { ProfilePage } from './ProfilePage'
export { SettingsPage } from './SettingsPage'
export { SubmitJokePage } from './SubmitJokePage'
export { NotFoundPage } from './NotFoundPage'

// Legacy components — preserved at /legacy/<path> mirror routes for reference.
// Will retire once the redesigned versions are reviewed and approved.
export { OnboardingPage } from './OnboardingPage'
export { HomePageLegacy } from './HomePageLegacy'
export { TrendingPageLegacy } from './TrendingPageLegacy'
export { FavoritesPageLegacy } from './FavoritesPageLegacy'
export { DraftsPageLegacy } from './DraftsPageLegacy'
export { ProfilePageLegacy } from './ProfilePageLegacy'
export { SettingsPageLegacy } from './SettingsPageLegacy'
export { SubmitJokePageLegacy } from './SubmitJokePageLegacy'
