#!/usr/bin/env node
/**
 * Build-time sitemap fetch.
 *
 * The sitemap is generated by the backend (GET {BACKEND_ORIGIN}/sitemap.xml)
 * but must be served from the frontend domain (robots.txt points crawlers at
 * https://jokesforfront.web.app/sitemap.xml). This script fetches it at
 * build time and writes it into public/sitemap.xml, so Vite copies it into
 * dist/ verbatim alongside the rest of the static site.
 *
 * Runs as the npm "prebuild" hook — npm runs it automatically before
 * "build" (tsc -b && vite build).
 *
 * FAIL-SOFT: on any problem (network failure, non-200, empty/non-XML body)
 * this prints a WARNING and exits 0 — it never fails the build. Any
 * existing public/sitemap.xml is left untouched. This matters because the
 * backend sitemap endpoint may not be deployed yet; a later build picks it
 * up once it is. We never want to ship an empty/garbage sitemap.xml.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const OUT_PATH = path.join(ROOT, 'public', 'sitemap.xml')
const FETCH_TIMEOUT_MS = 15_000

// Same fallback the frontend runtime uses (src/lib/seo/constants.ts) when
// VITE_API_URL isn't available.
const FALLBACK_API_URL = 'https://jokesforbackend-332865216810.us-east1.run.app/api/v1'

function warn(message) {
  console.warn(`[gen-sitemap] WARNING: ${message} — skipping, build continues.`)
}

/**
 * Best-effort read of VITE_API_URL. CI/deploy workflows set this explicitly
 * as a build-step env var, so process.env covers that case. For local dev
 * (where it typically only lives in .env, never exported to the shell) fall
 * back to a tiny manual parse of the repo-root .env file.
 */
function resolveApiUrl() {
  if (process.env.VITE_API_URL) return process.env.VITE_API_URL

  const envPath = path.join(ROOT, '.env')
  if (!existsSync(envPath)) return undefined

  try {
    const contents = readFileSync(envPath, 'utf-8')
    const match = contents.match(/^\s*VITE_API_URL\s*=\s*(.*)\s*$/m)
    if (!match) return undefined
    return match[1].trim().replace(/^["']|["']$/g, '')
  } catch {
    return undefined
  }
}

/** Derive the backend origin from VITE_API_URL by stripping a trailing /api/v1. */
function backendOrigin() {
  const apiUrl = resolveApiUrl() || FALLBACK_API_URL
  return apiUrl.replace(/\/api\/v1\/?$/, '')
}

async function main() {
  const origin = backendOrigin()
  const url = `${origin}/sitemap.xml`

  let res
  try {
    res = await fetch(url, { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) })
  } catch (err) {
    warn(`could not reach ${url} (${err instanceof Error ? err.message : String(err)})`)
    return
  }

  if (!res.ok) {
    warn(`${url} responded with HTTP ${res.status}`)
    return
  }

  const body = await res.text()
  const trimmed = body.trim()
  const looksLikeXml = trimmed.startsWith('<?xml') || trimmed.startsWith('<urlset')

  if (!trimmed || !looksLikeXml) {
    warn(`${url} did not return a valid-looking XML sitemap (empty or unexpected body)`)
    return
  }

  writeFileSync(OUT_PATH, body, 'utf-8')
  console.log(`[gen-sitemap] wrote ${OUT_PATH} from ${url} (${body.length} bytes)`)
}

main().catch((err) => {
  warn(`unexpected error (${err instanceof Error ? err.message : String(err)})`)
  process.exit(0)
})
